import StyleDictionary from 'style-dictionary';
import fs from 'fs';

// Helper: kebab-case to camelCase
function toCamelCase(str) {
  return str.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

function numericIfPossible(val) {
  if (typeof val === 'string' && val.endsWith('px')) {
    return Number(val.replace('px', ''));
  }
  return val;
}

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'amplify-creator',
      buildPath: 'dist/',
      files: [{ destination: 'variables.css', format: 'css/variables' }],
    },
    json: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{ destination: 'tokens.json', format: 'json/flat' }],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{ destination: 'tokens.js', format: 'javascript/es6' }],
    },
  },
});

await sd.buildAllPlatforms();

// Generate React Native output manually (Style Dictionary v4 custom formats are complex)
const colorsJson = JSON.parse(fs.readFileSync('tokens/colors.json', 'utf8'));
const typographyJson = JSON.parse(fs.readFileSync('tokens/typography.json', 'utf8'));

const colorEntries = Object.entries(colorsJson.color.sdui)
  .map(([key, val]) => {
    const camelKey = toCamelCase(key);
    return `  ${camelKey}: '${val.value}'`;
  })
  .join(',\n');

const sizeEntries = Object.entries(typographyJson.typography.size)
  .map(([key, val]) => {
    const num = numericIfPossible(val.value);
    const safeKey = /^\d/.test(key) ? `'${key}'` : key;
    return `  ${safeKey}: ${num}`;
  })
  .join(',\n');

const nativeOutput = [
  '// Auto-generated by @amplify/tokens-creator — do not edit',
  '',
  'export const colors = {',
  colorEntries,
  '};',
  '',
  'export const fontSize = {',
  sizeEntries,
  '};',
  '',
].join('\n');

fs.writeFileSync('dist/tokens.native.js', nativeOutput);
console.log('tokens-creator: build complete');
